"""MCP tool: import an asset generated by Hunyuan3D into Blender."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ImportGeneratedAssetHunyuanArgs(BaseModel):
    name: str = Field(description="The name of the object in scene.")
    zip_file_url: str = Field(description="The zip_file_url given in the generate model step.")


TOOL: dict[str, Any] = {
    "name": "import_generated_asset_hunyuan",
    "description": (
        "Import the asset generated by Hunyuan3D after the generation task is completed. "
        "Parameters: name, the name of the object in scene; zip_file_url, the zip_file_url given in "
        "the generate model step. Returns whether the asset has been imported successfully."
    ),
    "args": ImportGeneratedAssetHunyuanArgs,
}


def handle(arguments: dict[str, Any]) -> list[dict[str, Any]]:
    import json

    from freeglm_blender.loader import get_connection

    name = arguments.get("name")
    zip_file_url = arguments.get("zip_file_url")
    try:
        kwargs = {
            "name": name,
        }
        if zip_file_url:
            kwargs["zip_file_url"] = zip_file_url
        result = get_connection().send_command("import_generated_asset_hunyuan", kwargs)
        return [{"type": "text", "text": json.dumps(result, indent=2)}]
    except Exception as e:
        return [{"type": "text", "text": f"Error generating Hunyuan3D task: {str(e)}"}]
