#!/usr/bin/env python3
r"""
postcheck.py — ONE post-render gate that runs all math-tutorial checks that need the FINISHED video.

Run this from the project root AFTER `npx hyperframes render` has produced dist/output.mp4:

    python3 "$EDU_SKILL_ROOT/scripts/postcheck.py" dist

Why a separate runner from precheck.py: these checks operate on the RENDERED frames, not the source
HTML. The composition can pass every pre-render gate and still come out broken in the video — most
notably when a line/curve whose path `d` is generated by JS never gets drawn because the renderer
failed to load GSAP (the "有点、没线" bug). Only the actual pixels reveal it.

Exit 0 = all post-render checks passed. Exit 1 = a check failed or was skipped (not fully verified).

Self-correction loop:
    1. render → 2. run postcheck.py dist → 3. if it exits non-zero, read each FAIL block and fix
       (usually the renderer/GSAP loading or the composition's geometry JS) → 4. re-render →
    5. repeat until it prints "ALL POST-RENDER CHECKS PASSED".

Checks (each also runnable standalone):
    check_curves_rendered.py — a line/curve that should be drawn is actually present in output.mp4
                               (renderer-agnostic render-truth; catches JS-generated geometry that
                                never got painted, e.g. gsap not loaded → path stuck at d="M0 0").
    check_smooth_curve_render.py — a continuous curve (抛物线/双曲线/正弦/指数/反比例…) is RENDERED
                               smooth, not as a handful of straight chords (不要用分段直线逼近曲线).
                               Walks the actual rendered path geometry and flags jagged kinks; also
                               catches JS-generated curves the static pre-render gate cannot see.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

CHECKS = [
    ("check_curves_rendered.py",
     "Rendered lines/curves present in the video (线/曲线在成片里确实画出来了 — render-truth)"),
    ("check_smooth_curve_render.py",
     "Continuous curves rendered SMOOTH, not straight-chord polylines (曲线不能用折线逼近 — render-truth)"),
]


def _find_video(dist: Path, override: str | None) -> Path | None:
    if override:
        path = Path(override)
        return path if path.is_file() else None
    for name in ("output.mp4", "final.mp4", "video.mp4"):
        path = dist / name
        if path.is_file():
            return path
    videos = sorted(dist.glob("*.mp4"), key=lambda path: path.stat().st_size, reverse=True)
    return videos[0] if videos else None


def _preflight(dist: Path, video_override: str | None) -> list[str]:
    """Reject a missing render instead of letting every child check skip successfully."""
    if not dist.is_dir():
        return [f"dist directory does not exist: {dist}"]

    video = _find_video(dist, video_override)
    if video is None:
        requested = f": {video_override}" if video_override else f" under {dist}"
        return [f"rendered MP4 is missing{requested}"]
    if video.stat().st_size == 0:
        return [f"rendered MP4 is empty: {video}"]
    return []


def main() -> int:
    here = Path(__file__).resolve().parent
    dist = Path(sys.argv[1] if len(sys.argv) > 1 else "dist")
    video = sys.argv[2] if len(sys.argv) > 2 else None

    print("=" * 70)
    print(f"POSTCHECK — math-tutorial post-render gates on: {dist}")
    print("=" * 70)

    prerequisites = _preflight(dist, video)
    if prerequisites:
        print("POSTCHECK PREREQUISITE FAILED — validation did not run. DO NOT deliver yet.")
        for error in prerequisites:
            print(f"  - {error}")
        return 1

    results = []
    for script, desc in CHECKS:
        path = here / script
        if not path.exists():
            results.append((script, desc, 2, f"MISSING check script: {path}"))
            continue
        args = [sys.executable, str(path), str(dist)]
        if video:
            args.append(video)
        proc = subprocess.run(args, capture_output=True, text=True)
        results.append((script, desc, proc.returncode, (proc.stdout + proc.stderr).strip()))

    failed = []
    skipped = []
    for script, desc, rc, out in results:
        was_skipped = rc == 0 and "skipped" in out.lower()
        status = "SKIP" if was_skipped else ("PASS" if rc == 0 else "FAIL")
        if rc != 0:
            failed.append((script, desc, out))
        elif was_skipped:
            skipped.append((script, desc, out))
        print(f"[{status}] {desc}  ({script})")
        for line in out.splitlines():
            print(f"        {line}")

    print("-" * 70)
    if not failed and not skipped:
        print("ALL POST-RENDER CHECKS PASSED — safe to deliver.")
        return 0

    if skipped and not failed:
        print(f"POSTCHECK INCOMPLETE — {len(skipped)} check(s) were skipped. DO NOT claim fully verified.")
        return 1

    print(f"POSTCHECK FAILED — {len(failed)} check(s) need fixing. DO NOT deliver yet.")
    print(
        "Fix the renderer/composition, re-render, then re-run: ",
        sys.executable,
        Path(__file__).resolve(),
        dist,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
