#!/usr/bin/env python3
"""Generate the Markdown environment-variable tables from `src/shared/env.py`.

CONFIG_FIELDS in src/shared/env.py is the one declarative catalog of user-settable config vars
(key, secret, group, default, description). This script renders it as grouped Markdown tables on
stdout, for manual pasting into CLAUDE.md / docs — so the doc tables stop drifting from the code.

Usage:
    python3 scripts/gen_env_docs.py                 # print the Markdown tables to stdout
    python3 scripts/gen_env_docs.py --check [FILE…] # verify each FILE mentions every variable
                                                    # (default: CLAUDE.md); exit 1 on gaps

Stdlib-only; reads CONFIG_FIELDS via `ast` (no import of shared.env, no side effects).
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PY = REPO_ROOT / "src" / "shared" / "env.py"
DEFAULT_CHECK_FILES = [REPO_ROOT / "CLAUDE.md"]

# (key, secret, group, default, description) — mirrors the CONFIG_FIELDS comment in env.py.
Field = tuple[str, bool, str, str, str]


def load_config_fields(path: Path = ENV_PY) -> list[Field]:
    """Extract the literal CONFIG_FIELDS list from env.py without importing it."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            targets, value = node.targets, node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            targets, value = [node.target], node.value
        else:
            continue
        for target in targets:
            if isinstance(target, ast.Name) and target.id == "CONFIG_FIELDS":
                fields = ast.literal_eval(value)
                if not isinstance(fields, list):
                    raise SystemExit(f"error: CONFIG_FIELDS in {path} is not a list literal")
                return fields
    raise SystemExit(f"error: CONFIG_FIELDS not found in {path}")


def render(fields: list[Field]) -> str:
    """Render CONFIG_FIELDS as one Markdown table per group, in catalog order."""
    lines = [
        "<!-- Generated by scripts/gen_env_docs.py from src/shared/env.py CONFIG_FIELDS."
        " Regenerate instead of hand-editing rows. -->",
    ]
    current_group = None
    for key, secret, group, default, description in fields:
        if group != current_group:
            lines += ["", f"**{group}**", "", "| Variable | Default | Purpose |", "|----------|---------|---------|"]
            current_group = group
        purpose = f"{description} *(secret)*" if secret else description
        lines.append(f"| `{key}` | {default or '—'} | {purpose} |")
    return "\n".join(lines) + "\n"


def check(fields: list[Field], doc_paths: list[Path]) -> int:
    """Verify every catalog variable is mentioned in each doc; report gaps, return exit code."""
    status = 0
    for doc in doc_paths:
        if not doc.is_file():
            print(f"error: {doc}: file not found", file=sys.stderr)
            status = 1
            continue
        text = doc.read_text(encoding="utf-8")
        missing = [key for key, *_ in fields if key not in text]
        if missing:
            print(
                f"error: {doc.relative_to(REPO_ROOT) if doc.is_relative_to(REPO_ROOT) else doc}: "
                f"missing {len(missing)} variable(s): {', '.join(missing)}",
                file=sys.stderr,
            )
            status = 1
        else:
            print(
                f"ok: {doc.relative_to(REPO_ROOT) if doc.is_relative_to(REPO_ROOT) else doc}: "
                f"all {len(fields)} variables mentioned"
            )
    return status


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--check",
        nargs="*",
        metavar="FILE",
        default=None,
        help="verify each FILE mentions every CONFIG_FIELDS variable (default: CLAUDE.md); exit 1 on gaps",
    )
    args = parser.parse_args(argv)

    fields = load_config_fields()
    if args.check is None:
        sys.stdout.write(render(fields))
        return 0
    docs = [Path(p).resolve() for p in args.check] or DEFAULT_CHECK_FILES
    return check(fields, docs)


if __name__ == "__main__":
    raise SystemExit(main())
